# Работа с ошибками

* Ошибки (в программировании) - реакция системы на какую-либо некорректную ситуацию
  * Ошибки компиляции - когда неправильно написан исходный код

```
C:\Users\AiT\IdeaProjects\Lesson_19\src\ru.itis.users.app.Main.java:3:9
java: cannot find symbol
  symbol:   variable a
  location: class ru.itis.users.app.Main
```

  * Ошибки времени выполнения - происходит во время работы программы
    * Некорректные данные, которые программа получила извне

При вводе нулевого значения в качестве переменной `b` мы получим ошибку

```
Scanner scanner = new Scanner(System.in);

int a = scanner.nextInt();
int b = scanner.nextInt();

int c = a / b;
```

Текст ошибки

```
Exception in thread "main" java.lang.ArithmeticException: / by zero
	at ru.itis.users.app.Main.main(ru.itis.users.app.Main.java:10)
```

* Неправильно спроектированный код, который приводит к возникновению такой ситуации

```
int[] array = new int[5];

System.out.println(array[8]);
```

## Работа с ошибками времени выполнения

* Самостоятельный выброс ошибок (если это действительно нужно)
  * Например, вы не можете получить данные с внешнего сервиса, об этом нужно сообщить путем выброса ошибки
* Уметь обрабатывать различные ошибки, которые возникают в системе так, чтобы в целом она не упала

## В контексте Java

* Ошибки мы называем "исключениями"/"exception"
* Каждое исключение, возникающее в программе - это объект, экземпляр какого-либо класса
* Есть возможность писать собственные классы исключений
* Выбросить исключение - создать объект класса-исключения
* `IllegalArgumentException` - встроенный класс-исключений, применяется, как правило, для выброса исключений, связанных с входными данными
* `throw` - выброс исключения (создание объекта класса-исключения и передача его Java-машине)
* `RuntimeException` - встроенный класс-исключений, от которого мы должны наследоваться, чтобы создавать свои классы с походящими названиями
* Если нам необходимо гарантировать наличие сообщения в исключении, то надо реализовать конструктор, принимающий это сообщение

## Обработка исключнией

```
try {
    // код, в котором может возникнуть исключение
} catch (Exception e) {
    // код, который должен выполниться, если исключение появилось
}
```

* `Exception` - встроенный класс-исключение, который автоматически является предком для всех исключений